Release version v0.0.20+20

diff --git a/.github/workflows/build_auto.yml b/.github/workflows/build_auto.yml
--- a/.github/workflows/build_auto.yml
+++ b/.github/workflows/build_auto.yml
@@ -226,6 +226,12 @@ jobs:
           Icon=${{ env.APP_ID }}
           Categories=Utility;
           EOF
+
+          if [ ! -f "$APP_DIR/usr/share/applications/${{ env.APP_ID }}.desktop" ]; then
+            echo "Error: Desktop file creation failed"
+            exit 1
+          fi
+          echo "Desktop file created successfully: $APP_DIR/usr/share/applications/${{ env.APP_ID }}.desktop"
           
           # 复制图标
           cp assets/icon512.png $APP_DIR/usr/share/icons/hicolor/256x256/apps/${{ env.APP_ID }}.png
@@ -248,7 +254,7 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   build-windows:
-    name: Build Windows x86
+    name: Build Windows x64
     runs-on: windows-latest
     permissions:
       contents: write
@@ -274,7 +280,7 @@ jobs:
       - name: build Windows x86 
         run: |
           flutter build windows --release
-          Compress-Archive -Path build\windows\runner\Release\* -DestinationPath ${{ env.APP_NAME }}-windows-x86.zip
+          Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath ${{ env.APP_NAME }}-windows-x64.zip
 
       - name: upload Windows x86
         uses: softprops/action-gh-release@v1
@@ -282,7 +288,7 @@ jobs:
           tag_name: ${{ github.ref_name }}
           name: ${{ env.RELEASE_NAME }}
           generate_release_notes: true
-          files: ${{ env.APP_NAME }}-windows-x86.zip
+          files: ${{ env.APP_NAME }}-windows-x64.zip
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
